package com.pg.plantapps.nextactivitiesappservice.model.dao.rest;

import java.util.ArrayList;
import java.util.List;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestTemplate;

import com.pg.plantapps.nextactivitiesappservice.model.Unit;
import com.pg.plantapps.nextactivitiesappservice.model.dao.UnitDAO;


@Component
public class RestUnitDAO implements UnitDAO{

	private static class MyMachine {
		public String name;
		public Long assetId;
		public String type;
		public Long lineId;
		public String lineName;
	}

	private static class MyMachines {
		// data is the array object within the daily object
		public List<MyMachine> data;
	}
	
	private static final String BASE_URL = "https://pugophub:8444/mymachines-service-impl-0.6.5/myMachines/v1/units/preferred-units?previousPreferences=0&retrieveChildren=false";

	private RestTemplate restTemplate = new RestTemplate();
	
	@Override
	public List<Unit> getPreferredUnits() {
	
		String token = "eyJhbGciOiJSUzI1NiIsImprdSI6Imh0dHBzOi8vcHVnb3BodWIvdWFhL3Rva2VuX2tleXMiLCJraWQiOiJrZXktaWQtMSIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI5MzU4YmJiZjVkMTM0MTZlOTY2ZWFjM2IyY2EzOTQ4MSIsInN1YiI6IjQyMTkwNjlhLTRmMzctNGJjMC1hZmM5LTE5MmYwNzY5MDJmMCIsInNjb3BlIjpbIm1lcy5hcHByb3ZhbF9jb2NrcGl0LnVzZXIiLCJtZXMucm91dGVfbWFuYWdlbWVudC51c2VyIiwibWVzLnNlY3VyaXR5X21hbmFnZW1lbnQudXNlciIsIm1lcy5wcm9wZXJ0eV9kZWZpbml0aW9uLnVzZXIiLCJpcXAuY2xvdWR1c2VyIiwibWVzLmRvd250aW1lLnVzZXIiLCJjbG91ZF9jb250cm9sbGVyLndyaXRlIiwibWVzLm9wZXJhdGlvbnMudXNlciIsIm1lcy5hbmFseXNpcy51c2VyIiwibWVzLnJlcG9ydHMudXNlciIsIm1lcy5teV9tYWNoaW5lcy51c2VyIiwid2ViaG1pLnVzZXIiLCJzY2ltLnVzZXJpZHMiLCJtZXMuYWN0aXZpdGllcy51c2VyIiwiYm0tb3BlcmF0b3IiLCJvcGVuaWQiLCJpcXAudXNlciIsIndlYmhtaS5hZG1pbmlzdHJhdG9yIiwiY2xvdWRfY29udHJvbGxlci5yZWFkIiwicGFzc3dvcmQud3JpdGUiLCJtZXMubmNtX21hbmFnZW1lbnQudXNlciIsIm1lcy53YXN0ZS51c2VyIiwibWVzLmVxdWlwbWVudC51c2VyIiwibWVzLndvcmtfcXVldWUudXNlciIsImlxcC5kZXZlbG9wZXIiLCJtZXMub3JkZXJfbWFuYWdlbWVudC51c2VyIl0sImNsaWVudF9pZCI6InB1Z29waHViX21lcyIsImNpZCI6InB1Z29waHViX21lcyIsImF6cCI6InB1Z29waHViX21lcyIsInJldm9jYWJsZSI6dHJ1ZSwiZ3JhbnRfdHlwZSI6ImF1dGhvcml6YXRpb25fY29kZSIsInVzZXJfaWQiOiI0MjE5MDY5YS00ZjM3LTRiYzAtYWZjOS0xOTJmMDc2OTAyZjAiLCJvcmlnaW4iOiJ1YWEiLCJ1c2VyX25hbWUiOiJjb214Y2xpZW50IiwiZW1haWwiOiJjb214Y2xpZW50QHh4LmNvbSIsImF1dGhfdGltZSI6MTYxMjcxNTE5OSwicmV2X3NpZyI6IjE0YzVjNTllIiwiaWF0IjoxNjEyNzE1MjQ4LCJleHAiOjE2MTI3NTg0NDgsImlzcyI6Imh0dHBzOi8vcHVnb3BodWIvdWFhL29hdXRoL3Rva2VuIiwiemlkIjoidWFhIiwiYXVkIjpbIm1lcy5hcHByb3ZhbF9jb2NrcGl0IiwiY2xvdWRfY29udHJvbGxlciIsInNjaW0iLCJtZXMuYWN0aXZpdGllcyIsIm1lcy5yb3V0ZV9tYW5hZ2VtZW50IiwibWVzLmRvd250aW1lIiwib3BlbmlkIiwibWVzLnJlcG9ydHMiLCJtZXMud2FzdGUiLCJpcXAiLCJtZXMubXlfbWFjaGluZXMiLCJtZXMuZXF1aXBtZW50IiwibWVzLm9yZGVyX21hbmFnZW1lbnQiLCJwYXNzd29yZCIsInB1Z29waHViX21lcyIsIm1lcy53b3JrX3F1ZXVlIiwibWVzLmFuYWx5c2lzIiwibWVzLm5jbV9tYW5hZ2VtZW50IiwibWVzLnNlY3VyaXR5X21hbmFnZW1lbnQiLCJtZXMub3BlcmF0aW9ucyIsIm1lcy5wcm9wZXJ0eV9kZWZpbml0aW9uIiwid2ViaG1pIl19.d1mmUlCOHNNlxigW8vOsd2hF3xAXFeWlER4Cks0DQlXuH77ume4nLOMjtodje7pDp7z_R0jBogqvL4P7FM7yIzXi5NOOFNGfgSkpaN8hcTlYVlTWZnyVWs93r1aEXr0TUTaHTHUrhHxRJ3P3S-GJ0xg3RNEZNkxe0LGhPK-PgKUrblwmNfqxPJwgTOs4FZSTtGD3wt8c8ePHxLbG_5rESxgiXs7haPaMvJgN-QepHaBpYwe4WjTL_waq9BMFpYYOUCbSS_z70k-RqAD2_Jkwl8pJ_zqTjDXWJIZGI1WDznu7KbAL3cfvfiN44ueupNrMf-bipNcEoDJJ2NfouLlvzQ";
		MyMachines myMachines = restTemplate.getForObject(BASE_URL , MyMachines.class);
		
		List<Unit> results = new ArrayList<>();
		for (MyMachine mm : myMachines.data) {
			Unit unit = new Unit();
			unit.setUnitId(mm.assetId);	
			unit.setEquipment(mm.name);
			unit.setType(mm.type);
			unit.setLineId(mm.lineId);
			unit.setLine(mm.lineName);
			results.add(unit);		
		}
		
		return results;
	}

}

